### ISSUE TITLE
[Suggestion] - Add sound when a random occurence starts

### ISSUE THREAD

**Issue by Zoiter7** [GoldenCookieGIT/RandomOccurrences#3]
Some players might not notice when a random occurence starts, adding a sound will be helpfull

**Comment by GoldenCookieGIT** [comment]
Will include next update

**Comment by GoldenCookieGIT** [comment]
added in https://github.com/GoldenCookieGIT/RandomOccurrences/commit/684287427a6d08eafc8923a95a7d5e06c83c76d0
