### ISSUE TITLE
[Suggestion] - Show player score when ocurrence end

### ISSUE THREAD

**Issue by Zoiter7** [GoldenCookieGIT/RandomOccurrences#4]
When ocurrence ends, at the final top message, show the player score for know how many points the player did and maybe show the position of the ranking player ended.

**Comment by GoldenCookieGIT** [comment]
Will include next update

**Comment by GoldenCookieGIT** [comment]
added in https://github.com/GoldenCookieGIT/RandomOccurrences/commit/514fe6be871b97125da81cc5074144711c5a8c9a
