### ISSUE TITLE
Outdated version error bug on latests release

### ISSUE THREAD

**Issue by LadyHaley** [GoldenCookieGIT/RandomOccurrences#7]
![image](https://user-images.githubusercontent.com/3754909/233988180-846f55ec-95b5-4201-b0a5-2ef0a2c4383e.png)

**Comment by LadyHaley** [comment]
[11:50:19] [Craft Scheduler Thread - 55 - RandomOccurrences/INFO]: [RandomOccurrences] Unable to check for updates: Connection reset

**Comment by GoldenCookieGIT** [comment]
closing this as I cannot replicate this with my testing. Feel free to reopen if this issue persists.
